### PR TITLE
Task nxbt 2988 helm web ui

### PR DESCRIPTION
**Pull request by guirenard**

### CODE REVIEW

**Comment by ataillefer** [comment]
Sounds good!

**Review by ataillefer — DISMISSED** [review]

**Review by kevinleturc — DISMISSED** [review]
👌

**Comment by guirenard** [comment]
As per @kevinleturc advice, I adapted the versioning to be compatible with museum publishing.
See https://github.com/nuxeo/nuxeo-helm-charts/pull/15/commits/7c2050101a1add7a0bdf9bfe9c5773711207fd70

**Review by ataillefer — APPROVED** [review]

**Review by kevinleturc — APPROVED** [review]

**Review by nelsonsilva — APPROVED** [review]
Still needs follow up work to allow deploying both Nuxeo and Nuxeo Web UI charts

**Pull request merged**
